### PR TITLE
CS-Fixer: Check `Example` folder

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Review by Vitexus — APPROVED** [review]
Let's make all code best as we can :)

**Review by Vitexus — APPROVED** [review]
@OskarStark Oskar, I will use your configuration .php-cs-fixer.dist.php in my libraries as well.

**Review by Vitexus — APPROVED** [review]
Modern and clean PHP

**Comment by OskarStark** [comment]
> @OskarStark Oskar, I will use your configuration .php-cs-fixer.dist.php in my libraries as well.

Glad to hear that, but most work is done by @localheinz, as he is the maintainer of `ergebnis/php-cs-fixer-config` 👏

**Comment by slunak** [comment]
Thank you!

**Pull request merged**
