### PR TITLE
Run php-cs-fixer on src

### PR DESCRIPTION
**Pull request by slunak**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by slunak** [comment]
@OskarStark I am going to do a release now, but I will not include this PR. I think a lot of these constants should be private, so I will review them later.

**Comment by OskarStark** [comment]
From a code POV changing these constants to private are a BC break. So I would merge this PR as is and deprecate them somehow first before making them real private

**Comment by slunak** [comment]
hmm.. yeah, you are right, someone might have used them, even though they weren't supposed to.

**Comment by Vitexus** [comment]
Nice :) :+1:

**Comment by OskarStark** [comment]
You should add a @deprecated since X.Y. This constant will be private in X.Y

**Comment by slunak** [comment]
I will simply keep them public.

**Pull request merged**
