### PR TITLE
Enhancement: Add email to `@author` tags

### PR DESCRIPTION
**Pull request by OskarStark**
It is a good practice

### CODE REVIEW

**Review by Vitexus — APPROVED** [review]
agree

**Comment by OskarStark** [comment]
@Vitexus if you post your mail here, I can add it as well

**Comment by Vitexus** [comment]
> @Vitexus if you post your mail here, I can add it as well

**vitex@vitexsoftware.com**

**Comment by OskarStark** [comment]
> vitex@vitexsoftware.com

Done

**Comment by Vitexus** [comment]
> > [vitex@vitexsoftware.com](mailto:vitex@vitexsoftware.com)
> 
> Done

@slunak Looking forward for release :)

**Comment by slunak** [comment]
I am actually thinking to remove this at all... and instead create some sort of list of contributors or simply link here https://github.com/slunak/pushover-php/graphs/contributors. What do you think @OskarStark ?

**Comment by OskarStark** [comment]
Managing a manual list of contributors is cumbersome, while removing yours seems ok to me, I would allow other contributors to put `@author` tags

**Comment by OskarStark** [comment]
How is your decision here?

**Comment by slunak** [comment]
> How is your decision here?

Merging, thank you!

**Review by slunak — APPROVED** [review]

**Pull request merged**
